const id = "resources/index";
const collection = "pages";
const data = {name:"Resources",componentBlocks:[{discriminant:"shortHero",value:{backgroundImage:"/images/shortHeros/resources/componentBlocks/0/value/backgroundImage.jpg",title:"Resources"}},{discriminant:"movingChecklist",value:{header:"Moving Checklist",subtext:"Quick reference for steps to ensure your move goes off without a hitch",image:"/images/resources/resources/componentBlocks/1/value/image.webp",checklist:["All small and loose items are protected and boxed","A 'no pack' zone is designated for essentials (phone chargers, medicine, keys)","Boxes are sealed and labeled","Items in drawers and on shelves are cleared","Appliances are detached/unhooked","Gas/oil is removed from equipment","Flammable substances, ammunitions, explosives, and alcohol, are handled separately","Parking arrangements are secured","Property management/neighbors are aware of your move","If applicable, an elevator is explicitly reserved","Confirm no other work crews are scheduled at the same time as us","Pathways are clear, inside and outside load and unload sites","Sites are clean, sanitary, and safe","In the Winter, your driveway, walkways, and roads are plowed and salted/sanded"]}},{discriminant:"policiesAndContracts",value:{header:"Policies and Contracts",subtext:"We've outlined our Terms of Service and Full Value Replacement Coverage in simple language for quick reference. For interstate moves, the FMCSA also provides brochures regarding your legal rights.",localPolicies:[{title:"In State Terms and Conditions Outline",link:"#"},{title:"In State Full Value Replacement Coverage",link:"#"}],interstatePolicies:[{title:"Interstate Carrier Liability Agreement",link:"#"},{title:"\"Ready to Move\"",link:"#"},{title:"\"Your Rights and Responsiblities\"",link:"#"}],disclaimer:"We bill differently for interstate moves, as mandated by law. We will determine a flat rate and provide a quote, rather than create an hourly-based estimate."}}]};
const _internal = {
	type: 'data',
	filePath: "/Users/tedmartin/sites/localmovers/local-muscle-movers/src/content/pages/resources/index.yaml",
	rawData: "name: Resources\ncomponentBlocks:\n  - discriminant: shortHero\n    value:\n      backgroundImage: /images/shortHeros/resources/componentBlocks/0/value/backgroundImage.jpg\n      title: Resources\n  - discriminant: movingChecklist\n    value:\n      header: Moving Checklist\n      subtext: Quick reference for steps to ensure your move goes off without a hitch\n      image: /images/resources/resources/componentBlocks/1/value/image.webp\n      checklist:\n        - All small and loose items are protected and boxed\n        - >-\n          A 'no pack' zone is designated for essentials (phone chargers,\n          medicine, keys)\n        - Boxes are sealed and labeled\n        - Items in drawers and on shelves are cleared\n        - Appliances are detached/unhooked\n        - Gas/oil is removed from equipment\n        - >-\n          Flammable substances, ammunitions, explosives, and alcohol, are\n          handled separately\n        - Parking arrangements are secured\n        - Property management/neighbors are aware of your move\n        - If applicable, an elevator is explicitly reserved\n        - Confirm no other work crews are scheduled at the same time as us\n        - Pathways are clear, inside and outside load and unload sites\n        - Sites are clean, sanitary, and safe\n        - >-\n          In the Winter, your driveway, walkways, and roads are plowed and\n          salted/sanded\n  - discriminant: policiesAndContracts\n    value:\n      header: Policies and Contracts\n      subtext: >-\n        We've outlined our Terms of Service and Full Value Replacement Coverage\n        in simple language for quick reference. For interstate moves, the FMCSA\n        also provides brochures regarding your legal rights.\n      localPolicies:\n        - title: In State Terms and Conditions Outline\n          link: '#'\n        - title: In State Full Value Replacement Coverage\n          link: '#'\n      interstatePolicies:\n        - title: Interstate Carrier Liability Agreement\n          link: '#'\n        - title: '\"Ready to Move\"'\n          link: '#'\n        - title: '\"Your Rights and Responsiblities\"'\n          link: '#'\n      disclaimer: >-\n        We bill differently for interstate moves, as mandated by law. We will\n        determine a flat rate and provide a quote, rather than create an\n        hourly-based estimate.\n",
};

export { _internal, collection, data, id };
