const id = "home/index";
const collection = "pages";
const data = {name:"Home",componentBlocks:[{discriminant:"banner",value:{bannerImage:"/images/home/home/componentBlocks/0/value/bannerImage.jpeg",heading:"Let's get moving!!!",subheading:"At Local Muscle, we understand the serious responsibility placed upon us by the pandemic. We closely follow all state and federal guidelines and we've implemented enhanced sanitization routines.",buttonText:"Get Estimate!",buttonLink:"#"}},{discriminant:"imageText",value:{heading:"Trusted for over a decade",desciption:"We've built a reputation throughout New England as a moving company you can trust. Whether you're moving halfway across the country or across the street, we've got you covered. Throughout our history we've seen it all, and we use that experience to make your move as smooth as possible. Our customers return to us time and time again for their moving needs. Let our reviews speak for themselves: Check us out on Google Reviews and Yelp for more firsthand customer feedback!",imagePlacement:"right"}},{discriminant:"imageText",value:{heading:"Your Local Moving Team",desciption:"We build crews that work well together, and crews that work well together keep our customers happy. Our staff has experience with all kinds of moves, be it a top floor apartment in the middle of a city or a rural location with rougher terrain, we can handle it all.",imagePlacement:"left"}},{discriminant:"testimonialSelector",value:{testimonials:["anonymous-yelp-review","lee-van-dyke"]}}]};
const _internal = {
	type: 'data',
	filePath: "/Users/tedmartin/sites/localmovers/src/content/pages/home/index.yaml",
	rawData: "name: Home\ncomponentBlocks:\n  - discriminant: banner\n    value:\n      bannerImage: /images/home/home/componentBlocks/0/value/bannerImage.jpeg\n      heading: Let's get moving!!!\n      subheading: >-\n        At Local Muscle, we understand the serious responsibility placed upon us\n        by the pandemic. We closely follow all state and federal guidelines and\n        we've implemented enhanced sanitization routines.\n      buttonText: Get Estimate!\n      buttonLink: '#'\n  - discriminant: imageText\n    value:\n      heading: Trusted for over a decade\n      desciption: >-\n        We've built a reputation throughout New England as a moving company you\n        can trust. Whether you're moving halfway across the country or across\n        the street, we've got you covered. Throughout our history we've seen it\n        all, and we use that experience to make your move as smooth as possible.\n        Our customers return to us time and time again for their moving needs.\n        Let our reviews speak for themselves: Check us out on Google Reviews and\n        Yelp for more firsthand customer feedback!\n      imagePlacement: right\n  - discriminant: imageText\n    value:\n      heading: Your Local Moving Team\n      desciption: >-\n        We build crews that work well together, and crews that work well\n        together keep our customers happy. Our staff has experience with all\n        kinds of moves, be it a top floor apartment in the middle of a city or a\n        rural location with rougher terrain, we can handle it all.\n      imagePlacement: left\n  - discriminant: testimonialSelector\n    value:\n      testimonials:\n        - anonymous-yelp-review\n        - lee-van-dyke\n",
};

export { _internal, collection, data, id };
