const id = "home/index";
const collection = "pages";
const data = {name:"Home",componentBlocks:[{discriminant:"banner",value:{bannerImage:"/images/home/home/componentBlocks/0/value/bannerImage.webp",heading:"Let's get moving!",subheading:"\"You don't know how much you have to move until you go to move it.\" Local Muscle understands how challenging and stressful moving can be. That's why we work closely with our customers to understand their needs and the scope of their move to ensure we provide the right resources to help make it happen smoothly. Whether it's a small apartment or office move across town or a five bedroom house move out of state, we have you covered. Moving with Local Muscle is like moving with friends and that's why moving isn't just what we do for a living, it's what we live to do. ",buttonText:"Get an Estimate Today!",buttonLink:"/hire-us"}},{discriminant:"videoText",value:{video:"CLv16TFTKNs",heading:"Services Offered",description:"We've built a reputation throughout New England as a moving company you can trust. Whether you're moving halfway across the country or across the street, we've got you covered. Throughout our history we've seen it all, and we use that experience to make your move as smooth as possible. Our customers return to us time and time again for their moving needs. Let our reviews speak for themselves: Check us out on Google Reviews and Yelp for more firsthand customer feedback!",optionalLink:{link:"/join",text:"Contact sales to learn more"},type:"vertical"}},{discriminant:"serviceSelector",value:{services:["moving","heavy-items","rearrangement"]}},{discriminant:"testimonialCTA",value:{personName:"Lee Van Dyke",review:"We moved to our home in Portland just before Thanksgiving weekend. We scheduled our PODS arrivals in conjunction with our Local Muscle guys, and they were both on time, but worked with efficiency and intelligence. They were a joy to have around, if joy can be had when moving one's life possessions. What I mean to say is they were courteous, careful, and cheerful about the day. Great workers. I'd recommend them absolutely. And you know I'm telling you the truth, because I'm determined to not move again myself, any time soon. i.e. I have no motive other than to assist anyone considering hiring them.",testimonialType:"review"}}]};
const _internal = {
	type: 'data',
	filePath: "/Users/tedmartin/sites/local-muscle-movers/src/content/pages/home/index.yaml",
	rawData: "name: Home\ncomponentBlocks:\n  - discriminant: banner\n    value:\n      bannerImage: /images/home/home/componentBlocks/0/value/bannerImage.webp\n      heading: Let's get moving!\n      subheading: >-\n        \"You don't know how much you have to move until you go to move it.\"\n        Local Muscle understands how challenging and stressful moving can be.\n        That's why we work closely with our customers to understand their needs\n        and the scope of their move to ensure we provide the right resources to\n        help make it happen smoothly. Whether it's a small apartment or office\n        move across town or a five bedroom house move out of state, we have you\n        covered. Moving with Local Muscle is like moving with friends and that's\n        why moving isn't just what we do for a living, it's what we live to do. \n      buttonText: Get an Estimate Today!\n      buttonLink: /hire-us\n  - discriminant: videoText\n    value:\n      video: CLv16TFTKNs\n      heading: Services Offered\n      description: >-\n        We've built a reputation throughout New England as a moving company you\n        can trust. Whether you're moving halfway across the country or across\n        the street, we've got you covered. Throughout our history we've seen it\n        all, and we use that experience to make your move as smooth as possible.\n        Our customers return to us time and time again for their moving needs.\n        Let our reviews speak for themselves: Check us out on Google Reviews and\n        Yelp for more firsthand customer feedback!\n      optionalLink:\n        link: /join\n        text: Contact sales to learn more\n      type: vertical\n  - discriminant: serviceSelector\n    value:\n      services:\n        - moving\n        - heavy-items\n        - rearrangement\n  - discriminant: testimonialCTA\n    value:\n      personName: Lee Van Dyke\n      review: >-\n        We moved to our home in Portland just before Thanksgiving weekend. We\n        scheduled our PODS arrivals in conjunction with our Local Muscle guys,\n        and they were both on time, but worked with efficiency and intelligence.\n        They were a joy to have around, if joy can be had when moving one's life\n        possessions. What I mean to say is they were courteous, careful, and\n        cheerful about the day. Great workers. I'd recommend them absolutely.\n        And you know I'm telling you the truth, because I'm determined to not\n        move again myself, any time soon. i.e. I have no motive other than to\n        assist anyone considering hiring them.\n      testimonialType: review\n",
};

export { _internal, collection, data, id };
