const id = "about/index";
const collection = "pages";
const data = {name:"About",componentBlocks:[{discriminant:"shortHero",value:{backgroundImage:"/images/shortHeros/about/componentBlocks/0/value/backgroundImage.jpg",title:"Meet the Muscle"}},{discriminant:"videoText",value:{video:"zsexg2uA4ak",heading:"Our story, in storage units",description:"No doubt we're well acquainted with storage units. Ten years ago our story started in one. Founding partner Alex Sargent got the idea to start a moving company after overhearing complaints about the moving experience and attitude of the movers people had hired. Ned Swain, a frequent customer, liked the idea so much he brought it to two other friends, Jake Holz and Jon Donnell. Soon after, Local Muscle was born with the driving idea that customer service and attitude of the crews will be what sets us apart. The results speak for themselves.",optionalLink:{}}},{discriminant:"headerText",value:{header:"Our Mission",text:"To provide a stress free and cost effective move that leaves you wondering what you were worried about in the first place."}},{discriminant:"headerText",value:{header:"Why choose Local Muscle?",text:"We've built a reputation throughout New England as a moving company you can trust. Whether you're moving halfway across the country or across the street, we've got you covered.Throughout our history we really have seen it all, and use that knowledge to make your move as smooth as possible.Many of our customers have returned to us time and time again for their moving needs. That being said, we prefer to let our reviews speak for themselves. Check us out on Google Reviews and Yelp for more firsthand customer feedback!\n\nPut simply, we want to change your opinion of movers and moving for the better. Each move is carefully tailored to best fit your needs and ensure a positive experience for customers and crews alike. From the point you complete our estimate form, a member of our dedicated staff will be in contact with you every step of the way. Get started with our estimate form."}},{discriminant:"testimonialCTA",value:{personName:"Ned Swain",review:"\"I love lifting heavy awkward things, and running around.\""}}]};
const _internal = {
	type: 'data',
	filePath: "/Users/tedmartin/sites/local-muscle-movers/src/content/pages/about/index.yaml",
	rawData: "name: About\ncomponentBlocks:\n  - discriminant: shortHero\n    value:\n      backgroundImage: /images/shortHeros/about/componentBlocks/0/value/backgroundImage.jpg\n      title: Meet the Muscle\n  - discriminant: videoText\n    value:\n      video: zsexg2uA4ak\n      heading: Our story, in storage units\n      description: >-\n        No doubt we're well acquainted with storage units. Ten years ago our\n        story started in one. Founding partner Alex Sargent got the idea to\n        start a moving company after overhearing complaints about the moving\n        experience and attitude of the movers people had hired. Ned Swain, a\n        frequent customer, liked the idea so much he brought it to two other\n        friends, Jake Holz and Jon Donnell. Soon after, Local Muscle was born\n        with the driving idea that customer service and attitude of the crews\n        will be what sets us apart. The results speak for themselves.\n      optionalLink: {}\n  - discriminant: headerText\n    value:\n      header: Our Mission\n      text: >-\n        To provide a stress free and cost effective move that leaves you\n        wondering what you were worried about in the first place.\n  - discriminant: headerText\n    value:\n      header: Why choose Local Muscle?\n      text: >-\n        We've built a reputation throughout New England as a moving company you\n        can trust. Whether you're moving halfway across the country or across\n        the street, we've got you covered.Throughout our history we really have\n        seen it all, and use that knowledge to make your move as smooth as\n        possible.Many of our customers have returned to us time and time again\n        for their moving needs. That being said, we prefer to let our reviews\n        speak for themselves. Check us out on Google Reviews and Yelp for more\n        firsthand customer feedback!\n\n\n        Put simply, we want to change your opinion of movers and moving for the\n        better. Each move is carefully tailored to best fit your needs and\n        ensure a positive experience for customers and crews alike. From the\n        point you complete our estimate form, a member of our dedicated staff\n        will be in contact with you every step of the way. Get started with our\n        estimate form.\n  - discriminant: testimonialCTA\n    value:\n      personName: Ned Swain\n      review: '\"I love lifting heavy awkward things, and running around.\"'\n",
};

export { _internal, collection, data, id };
